version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: git submodule update --init --recursive & cmake -G "Visual Studio 15 2017"
build:
  project: PACKAGE.vcxproj
  verbosity: minimal
after_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    set LOC=%APPVEYOR_BUILD_FOLDER%/bin/%CONFIGURATION%/

    set ZIPNAME=set09121_%CONFIGURATION%_%APPVEYOR_REPO_COMMIT%.zip

    7z a %ZIPNAME% %LOC%/*.exe %LOC%/*.dll %LOC%/*
artifacts:
- path: '*.zip'
  name: zip
deploy:
- provider: GitHub
  description: First try at GitHub Deployment
  auth_token:
    secure: qjlAVcgnafDDLEjvW1N8Agmoju7/zFBEfC+58E8GT3fto5Uy014NdL/ZAXKjzBZE
  prerelease: true